### ISSUE TITLE
weaviate-cli results in an error

### ISSUE THREAD

**Issue by michaverhagen** [semi-technologies/weaviate-cli#46]
weaviate-cli empty results in an error. This is the error message I get:
```
Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/micha/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weaviate-cli", line 164, in <module>
    main()
  File "/usr/local/bin/weaviate-cli", line 145, in main
    Empty(Init().loadConfig(False, None)).Run(options.force)
  File "/home/micha/weaviate-cli/modules/Empty.py", line 61, in Run
    self.emptyWeaviate("things")
  File "/home/micha/weaviate-cli/modules/Empty.py", line 51, in emptyWeaviate
    self.emptyWeaviate(conceptType)
  File "/home/micha/weaviate-cli/modules/Empty.py", line 43, in emptyWeaviate
    statusCode = self.weaviate.Delete("/" + conceptType + "/" + concept["id"])
  File "/home/micha/weaviate-cli/modules/Weaviate.py", line 142, in Delete
    request = requests.delete(self.config["url"] + "/v1" + path, headers=self.getHeadersForRequest(shouldAuthenticate))
  File "/home/micha/.local/lib/python3.6/site-packages/requests/api.py", line 158, in delete
    return request('delete', url, **kwargs)
  File "/home/micha/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/micha/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/micha/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/micha/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by StanSilas** [comment]
@michaverhagen  were you able to figure out what the cause was and what this error was trying to tell us?
Thank you

**Comment by michaverhagen** [comment]
No not yet. I may dive into it in the coming month.

**Comment by fefi42** [comment]
The CLI has been massively rewritten and is now pip installable:
Install using: pip install weaviate-cli
Run using: weaviate-cli --help

I assume this issue is now resolved if there is still a problem please reopen.
