### ISSUE TITLE
No module named 'weaviate.tools' when running `weaviate data delete`

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-cli#49]
When running `weaviate data delete` with the latest version of the CLI I get the error message:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/weaviate", line 5, in <module>
    from cli import main
  File "/opt/homebrew/lib/python3.9/site-packages/cli.py", line 5, in <module>
    from semi.commands.data import delete_all_data, import_data_from_file
  File "/opt/homebrew/lib/python3.9/site-packages/semi/commands/data.py", line 4, in <module>
    import weaviate.tools
ModuleNotFoundError: No module named 'weaviate.tools'
```

**Comment by StefanBogdan** [comment]
The error is thrown because the CLI is not compatible with `weaviate-client` version 3.0.0. I fixed it with a patch so now it should be fine if you use `weaviate-cli` version 2.1.2: https://pypi.org/project/weaviate-cli/2.1.2/
